'use client';

import React, { useState, useEffect } from 'react';
import {
    Dialog,
    DialogContent,
    DialogDescription,
    DialogFooter,
    DialogHeader,
    DialogTitle,
} from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Label } from '@/components/ui/label';
import { resumeApi, applicationApi, aiApi, Resume, Job } from '@/lib/api';
import { toast } from 'sonner';
import {
    Send,
    FileText,
    Loader2,
    CheckCircle2,
    Briefcase,
    ChevronDown,
    Sparkles,
    RefreshCw,
    Eye,
    Edit3,
    Zap
} from 'lucide-react';
import { FeedbackModal } from './FeedbackModal';
import { TypewriterText } from './TypewriterText';

interface ApplyModalProps {
    open: boolean;
    onOpenChange: (open: boolean) => void;
    jobs: Job[];  // Can be single job or multiple jobs for bulk apply
    onSuccess?: () => void;
}

export function ApplyModal({ open, onOpenChange, jobs, onSuccess }: ApplyModalProps) {
    const [resumes, setResumes] = useState<Resume[]>([]);
    const [selectedResumeId, setSelectedResumeId] = useState<number | null>(null);
    const [coverLetter, setCoverLetter] = useState('');
    const [useAutoGenerated, setUseAutoGenerated] = useState(true);
    const [loading, setLoading] = useState(false);
    const [loadingResumes, setLoadingResumes] = useState(true);

    // AI-specific states
    const [aiCoverLetter, setAiCoverLetter] = useState('');
    const [generatingAI, setGeneratingAI] = useState(false);
    const [aiGenerated, setAiGenerated] = useState(false);
    const [showPreview, setShowPreview] = useState(false);
    const [isEditing, setIsEditing] = useState(false);
    const [matchScore, setMatchScore] = useState<number | null>(null);
    const [loadingMatchScore, setLoadingMatchScore] = useState(false);
    const [showFeedbackModal, setShowFeedbackModal] = useState(false);
    const [isTyping, setIsTyping] = useState(false);

    const isBulk = jobs.length > 1;

    useEffect(() => {
        if (open) {
            fetchResumes();
            setCoverLetter('');
            setUseAutoGenerated(true);
            setAiCoverLetter('');
            setAiGenerated(false);
            setShowPreview(false);
            setIsEditing(false);
            setMatchScore(null);
            setIsTyping(false);
        }
    }, [open]);

    // Fetch match score when resume and job are selected (single job only)
    useEffect(() => {
        if (open && selectedResumeId && jobs.length === 1 && !isBulk) {
            fetchMatchScore();
        }
    }, [open, selectedResumeId, jobs]);

    const fetchMatchScore = async () => {
        if (!selectedResumeId || jobs.length !== 1) return;

        try {
            setLoadingMatchScore(true);
            const result = await aiApi.getMatchScore({
                job_id: jobs[0].id,
                resume_id: selectedResumeId
            });
            setMatchScore(result.overall_score);
        } catch (error) {
            console.error('Failed to fetch match score:', error);
        } finally {
            setLoadingMatchScore(false);
        }
    };

    const fetchResumes = async () => {
        try {
            setLoadingResumes(true);
            const data = await resumeApi.getAll();
            setResumes(data);
            // Auto-select active resume or first resume
            const activeResume = data.find(r => r.is_active);
            if (activeResume) {
                setSelectedResumeId(activeResume.id);
            } else if (data.length > 0) {
                setSelectedResumeId(data[0].id);
            }
        } catch (error) {
            toast.error('Failed to load resumes');
        } finally {
            setLoadingResumes(false);
        }
    };

    const generatePreviewCoverLetter = () => {
        if (jobs.length === 0) return '';
        const job = jobs[0];
        return `Dear ${job.company} Hiring Team,

I am writing to express my strong interest in the ${job.title} position at ${job.company}. I am confident that my skills and experience make me an excellent candidate for this role.

Please find my resume attached for your review. I am excited about the opportunity to contribute to your team and would welcome the chance to discuss how my background aligns with your needs.

Thank you for considering my application. I look forward to hearing from you.

Best regards`;
    };

    const generateAICoverLetter = async () => {
        if (!selectedResumeId || jobs.length === 0) {
            toast.error('Please select a resume first');
            return;
        }

        try {
            setGeneratingAI(true);
            const result = await aiApi.generateCoverLetter({
                job_id: jobs[0].id,
                resume_id: selectedResumeId
            });
            setAiCoverLetter(result.cover_letter);
            setCoverLetter(result.cover_letter);
            setAiGenerated(true);
            setShowPreview(true);
            setIsTyping(true);
            toast.success('AI cover letter generated!');
        } catch (error: any) {
            toast.error(error.response?.data?.error || 'Failed to generate cover letter');
        } finally {
            setGeneratingAI(false);
        }
    };

    const regenerateWithFeedback = async (feedback: string) => {
        if (!selectedResumeId || jobs.length === 0 || !aiCoverLetter) return;

        try {
            setGeneratingAI(true);
            const result = await aiApi.regenerateCoverLetter({
                job_id: jobs[0].id,
                resume_id: selectedResumeId,
                previous_letter: aiCoverLetter,
                feedback
            });
            setAiCoverLetter(result.cover_letter);
            setCoverLetter(result.cover_letter);
            setIsTyping(true);
            toast.success('Cover letter regenerated!');
        } catch (error: any) {
            toast.error(error.response?.data?.error || 'Failed to regenerate cover letter');
        } finally {
            setGeneratingAI(false);
        }
    };

    const getMatchScoreColor = (score: number) => {
        if (score >= 80) return 'text-green-600 bg-green-100 dark:text-green-400 dark:bg-green-900/30';
        if (score >= 60) return 'text-blue-600 bg-blue-100 dark:text-blue-400 dark:bg-blue-900/30';
        if (score >= 40) return 'text-amber-600 bg-amber-100 dark:text-amber-400 dark:bg-amber-900/30';
        return 'text-red-600 bg-red-100 dark:text-red-400 dark:bg-red-900/30';
    };

    const handleSubmit = async () => {
        if (!selectedResumeId) {
            toast.error('Please select a resume');
            return;
        }

        setLoading(true);
        try {
            // Determine which cover letter to use
            let finalCoverLetter = '';
            if (aiGenerated) {
                finalCoverLetter = coverLetter; // Use edited AI letter
            } else if (!useAutoGenerated) {
                finalCoverLetter = coverLetter; // Use custom letter
            }
            // If useAutoGenerated and not aiGenerated, empty string lets backend auto-generate

            if (isBulk) {
                // Bulk application
                await applicationApi.createBulk({
                    job_ids: jobs.map(j => j.id),
                    resume_id: selectedResumeId,
                    cover_letter: finalCoverLetter,
                });
                toast.success(`Successfully applied to ${jobs.length} jobs!`);
            } else {
                // Single application
                await applicationApi.create({
                    job: jobs[0].id,
                    resume: selectedResumeId,
                    cover_letter: finalCoverLetter,
                });
                toast.success(`Application submitted for ${jobs[0].title}!`);
            }
            onOpenChange(false);
            onSuccess?.();
        } catch (error: any) {
            const message = error.response?.data?.job_ids?.[0]
                || error.response?.data?.detail
                || error.response?.data?.non_field_errors?.[0]
                || 'Failed to submit application';
            toast.error(message);
        } finally {
            setLoading(false);
        }
    };

    return (
        <Dialog open={open} onOpenChange={onOpenChange}>
            <DialogContent className="rounded-[2rem] glass border-white/20 max-w-3xl max-h-[90vh] overflow-y-auto">
                <DialogHeader>
                    <DialogTitle className="text-xl flex items-center gap-2">
                        <Send className="w-5 h-5 text-primary" />
                        {isBulk ? `Apply to ${jobs.length} Jobs` : 'Submit Application'}
                    </DialogTitle>
                    <DialogDescription>
                        {isBulk
                            ? 'You are about to apply to multiple positions with your selected resume.'
                            : `Apply for ${jobs[0]?.title} at ${jobs[0]?.company}`}
                    </DialogDescription>
                </DialogHeader>

                <div className="space-y-6 py-4">
                    {/* Jobs Summary (for bulk) */}
                    {isBulk && (
                        <div className="space-y-2">
                            <Label className="text-sm font-medium">Selected Jobs</Label>
                            <div className="max-h-32 overflow-y-auto space-y-2 p-3 rounded-xl bg-secondary/50 border border-border/50">
                                {jobs.map((job) => (
                                    <div key={job.id} className="flex items-center gap-2 text-sm">
                                        <Briefcase className="w-4 h-4 text-primary shrink-0" />
                                        <span className="font-medium truncate">{job.title}</span>
                                        <span className="text-muted-foreground truncate">at {job.company}</span>
                                    </div>
                                ))}
                            </div>
                        </div>
                    )}

                    {/* Resume Selection */}
                    <div className="space-y-2">
                        <Label className="text-sm font-medium">Select Resume</Label>
                        {loadingResumes ? (
                            <div className="flex items-center gap-2 p-3 rounded-xl bg-secondary/50 border border-border/50">
                                <Loader2 className="w-4 h-4 animate-spin" />
                                <span className="text-sm text-muted-foreground">Loading resumes...</span>
                            </div>
                        ) : resumes.length === 0 ? (
                            <div className="p-4 rounded-xl bg-amber-500/10 border border-amber-500/20 text-amber-700 dark:text-amber-400 text-sm">
                                <p className="font-medium">No resumes found</p>
                                <p className="text-xs mt-1">Please create a resume first before applying to jobs.</p>
                            </div>
                        ) : (
                            <div className="relative">
                                <select
                                    value={selectedResumeId ?? ''}
                                    onChange={(e) => setSelectedResumeId(Number(e.target.value))}
                                    className="w-full h-12 px-4 pr-10 rounded-xl border border-input bg-background text-sm font-medium focus:outline-none focus:ring-2 focus:ring-ring appearance-none cursor-pointer"
                                >
                                    {resumes.map((resume) => (
                                        <option key={resume.id} value={resume.id}>
                                            {resume.title} {resume.is_active ? '(Active)' : ''}
                                        </option>
                                    ))}
                                </select>
                                <ChevronDown className="absolute right-3 top-1/2 -translate-y-1/2 w-5 h-5 text-muted-foreground pointer-events-none" />
                            </div>
                        )}
                    </div>

                    {/* Cover Letter Option */}
                    <div className="space-y-3">
                        <div className="flex items-center justify-between">
                            <Label className="text-sm font-medium">Cover Letter</Label>
                            {!isBulk && matchScore !== null && (
                                <div className={`px-2 py-1 rounded-lg text-xs font-semibold flex items-center gap-1 ${getMatchScoreColor(matchScore)}`}>
                                    <Zap className="w-3 h-3" />
                                    {matchScore}% Match
                                </div>
                            )}
                            {!isBulk && loadingMatchScore && (
                                <div className="px-2 py-1 rounded-lg text-xs text-muted-foreground flex items-center gap-1">
                                    <Loader2 className="w-3 h-3 animate-spin" />
                                    Computing match...
                                </div>
                            )}
                        </div>

                        <div className="flex gap-2">
                            <Button
                                type="button"
                                variant={useAutoGenerated && !aiGenerated ? 'default' : 'outline'}
                                size="sm"
                                onClick={() => {
                                    setUseAutoGenerated(true);
                                    setAiGenerated(false);
                                    setShowPreview(false);
                                }}
                                className="rounded-xl flex-1"
                            >
                                <CheckCircle2 className="w-4 h-4 mr-2" />
                                Auto-generate
                            </Button>
                            {!isBulk && (
                                <Button
                                    type="button"
                                    variant={aiGenerated ? 'default' : 'outline'}
                                    size="sm"
                                    onClick={generateAICoverLetter}
                                    disabled={generatingAI || !selectedResumeId}
                                    className="rounded-xl flex-1 bg-gradient-to-r from-purple-500 to-pink-500 hover:from-purple-600 hover:to-pink-600 text-white border-0"
                                >
                                    {generatingAI ? (
                                        <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                                    ) : (
                                        <Sparkles className="w-4 h-4 mr-2" />
                                    )}
                                    AI Generate
                                </Button>
                            )}
                            <Button
                                type="button"
                                variant={!useAutoGenerated && !aiGenerated ? 'default' : 'outline'}
                                size="sm"
                                onClick={() => {
                                    setUseAutoGenerated(false);
                                    setAiGenerated(false);
                                    if (!coverLetter) {
                                        setCoverLetter(generatePreviewCoverLetter());
                                    }
                                }}
                                className="rounded-xl flex-1"
                            >
                                <Edit3 className="w-4 h-4 mr-2" />
                                Custom
                            </Button>
                        </div>

                        {useAutoGenerated && !aiGenerated ? (
                            <div className="p-4 rounded-xl bg-secondary/50 border border-border/50">
                                <p className="text-sm text-muted-foreground">
                                    A personalized cover letter will be automatically generated based on the job details and your profile.
                                </p>
                            </div>
                        ) : aiGenerated && showPreview ? (
                            <div className="space-y-3">
                                <div className="p-4 rounded-xl bg-gradient-to-br from-purple-50 to-pink-50 dark:from-purple-900/20 dark:to-pink-900/20 border border-purple-200/50 dark:border-purple-800/50">
                                    <div className="flex items-center justify-between mb-3">
                                        <div className="flex items-center gap-2 text-sm text-purple-700 dark:text-purple-300">
                                            <Sparkles className="w-4 h-4" />
                                            <span className="font-medium">AI-Generated Cover Letter</span>
                                        </div>
                                        <div className="flex gap-2">
                                            <Button
                                                type="button"
                                                variant="ghost"
                                                size="sm"
                                                onClick={() => setIsEditing(!isEditing)}
                                                className="h-7 px-2 text-xs"
                                            >
                                                {isEditing ? <Eye className="w-3 h-3 mr-1" /> : <Edit3 className="w-3 h-3 mr-1" />}
                                                {isEditing ? 'Preview' : 'Edit'}
                                            </Button>
                                            <Button
                                                type="button"
                                                variant="ghost"
                                                size="sm"
                                                onClick={() => setShowFeedbackModal(true)}
                                                disabled={generatingAI}
                                                className="h-7 px-2 text-xs"
                                            >
                                                <RefreshCw className={`w-3 h-3 mr-1 ${generatingAI ? 'animate-spin' : ''}`} />
                                                Regenerate
                                            </Button>
                                        </div>
                                    </div>
                                    {isEditing ? (
                                        <textarea
                                            value={coverLetter}
                                            onChange={(e) => setCoverLetter(e.target.value)}
                                            rows={10}
                                            className="w-full px-3 py-2 rounded-lg border border-purple-200 dark:border-purple-700 bg-white dark:bg-gray-900 text-sm focus:outline-none focus:ring-2 focus:ring-purple-500 resize-none"
                                        />
                                    ) : (
                                        <div className="max-h-48 overflow-y-auto text-sm text-gray-700 dark:text-gray-300 whitespace-pre-wrap">
                                            {isTyping ? (
                                                <TypewriterText
                                                    text={coverLetter}
                                                    speed={5}
                                                    onComplete={() => setIsTyping(false)}
                                                />
                                            ) : (
                                                coverLetter
                                            )}
                                        </div>
                                    )}
                                </div>
                            </div>
                        ) : (
                            <textarea
                                value={coverLetter}
                                onChange={(e) => setCoverLetter(e.target.value)}
                                placeholder="Write your cover letter..."
                                rows={8}
                                className="w-full px-4 py-3 rounded-xl border border-input bg-background text-sm focus:outline-none focus:ring-2 focus:ring-ring resize-none"
                            />
                        )}
                    </div>
                </div>

                <DialogFooter className="flex gap-3 sm:gap-3">
                    <Button
                        variant="outline"
                        onClick={() => onOpenChange(false)}
                        className="rounded-xl flex-1"
                        disabled={loading}
                    >
                        Cancel
                    </Button>
                    <Button
                        onClick={handleSubmit}
                        disabled={loading || !selectedResumeId || resumes.length === 0}
                        className="rounded-xl flex-1 bg-primary hover:bg-primary/90"
                    >
                        {loading ? (
                            <>
                                <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                                Submitting...
                            </>
                        ) : (
                            <>
                                <Send className="w-4 h-4 mr-2" />
                                {isBulk ? `Apply to ${jobs.length} Jobs` : 'Submit Application'}
                            </>
                        )}
                    </Button>
                </DialogFooter>
            </DialogContent>

            <FeedbackModal
                open={showFeedbackModal}
                onOpenChange={setShowFeedbackModal}
                onSubmit={regenerateWithFeedback}
                loading={generatingAI}
            />
        </Dialog>
    );
}
