# Generated by Django 6.0.1 on 2026-01-28 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_job_options_application'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='application',
            name='ai_generated_cover_letter',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='application',
            name='match_breakdown',
            field=models.JSONField(blank=True, default=dict, help_text='Detailed match score breakdown'),
        ),
        migrations.AddField(
            model_name='application',
            name='match_score',
            field=models.FloatField(blank=True, help_text='AI-computed match score (0-100)', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='embedding',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
