# Generated by Django 6.0.1 on 2026-01-28 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_resume_email_resume_links_resume_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='embedding',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
